apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: yxal
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yxal
    app.kubernetes.io/part-of: byoc-app-spqh
  name: yxal
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: yxal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: yxal
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xwkm-tenant/byoc-app-spqh/yxal@sha256:5f4d2bddf82e3ff9d3855c4fbb02e1d522389070d3b37990de6ebd9b4e404292
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
